local helpers = require("test.helpers")

describe("re-numbering", function()
  before_each(function()
    helpers.reset_config()
  end)

  it("renumbers a selected list correctly", function()
    helpers.new_buffer({
      "# Hello there",
      "33. this is the first bullet",
      "2. this is the second bullet",
      "1.     this is the third bullet",
      "4. this is the fourth bullet",
    })
    helpers.feedkeys("ggVGgN")
    assert.are.same({
      "# Hello there",
      "1. this is the first bullet",
      "2. this is the second bullet",
      "3. this is the third bullet",
      "4. this is the fourth bullet",
    }, helpers.get_lines())
  end)

  it("renumbers a list containing checkboxes", function()
    helpers.new_buffer({
      "# Hello there",
      "33. this is the first bullet",
      "- [x] this is the second bullet",
      "1.     this is the third bullet",
      "  - [ ] this is the fourth bullet",
      "4. this is the fifth bullet",
      "",
      "- [o] second bullet list",
      "b. second item",
      "- [x] third item",
    })
    -- cursor is at line 10; move to line 2 (j from line 1 = line 2)
    helpers.feedkeys("ggj")
    helpers.feedkeys("gN")
    helpers.feedkeys("}j")
    helpers.feedkeys("gN")
    assert.are.same({
      "# Hello there",
      "1. this is the first bullet",
      "- [x] this is the second bullet",
      "2. this is the third bullet",
      "  - [ ] this is the fourth bullet",
      "3. this is the fifth bullet",
      "",
      "- [o] second bullet list",
      "a. second item",
      "- [x] third item",
    }, helpers.get_lines())
  end)

  it("renumbers a nested list", function()
    vim.g.bullets_line_spacing = 2
    helpers.new_buffer({
      "# Hello there",
      "0. zero bullet",
      "",
      "X. first bullet",
      "",
      "- second bullet",
      "\twrapped line",
      "",
      "a. third bullet",
      "",
      "I. fourth bullet",
      "",
      "\tV. fifth bullet",
      "",
      "\t\tB. sixth bullet",
      "",
      "\t* seventh bullet",
      "",
      "\t\ti. eighth bullet",
      "",
      "\t\tx. ninth bullet",
      "\t\t\t wrapped line",
      "",
      "\t\t\ta. tenth bullet",
      "wrapped line without indent",
      "",
      "\tC. eleventh bullet",
      "\t\t0. twelfth bullet",
      "",
      "\t\t\t* thirteenth bullet",
      "",
      "\t\t\t\t+ fourteenth bullet",
      "",
      "\t\t\tb. fifteenth bullet",
      "",
      "\t\ta. sixteenth bullet",
      "",
      "\t\t\t8. seventeenth bullet",
      "",
      "\t\t\t0. eighteenth bullet",
      "\t\t\t\t wrapped line",
      "",
      "\tnormal indented line",
      "next normal line",
      "",
      "1. nineteenth bullet",
      "",
      "x. twentieth bullet",
      "",
      "",
      "v. twenty-first bullet",
      "- twenty-second bullet",
      "",
      "",
      "v. twenty-third bullet",
    })
    -- Go to line 4 (gg then 3j from line 1) and renumber from there
    helpers.feedkeys("gg3j")
    helpers.feedkeys("gN")
    -- Go to last line then 3k up and renumber
    helpers.feedkeys("G3k")
    helpers.feedkeys("gN")
    assert.are.same({
      "# Hello there",
      "1. zero bullet",
      "",
      "2. first bullet",
      "",
      "- second bullet",
      "\twrapped line",
      "",
      "3. third bullet",
      "",
      "4. fourth bullet",
      "",
      "\tI. fifth bullet",
      "",
      "\t\tA. sixth bullet",
      "",
      "\t* seventh bullet",
      "",
      "\t\ti. eighth bullet",
      "",
      "\t\tii. ninth bullet",
      "\t\t\t wrapped line",
      "",
      "\t\t\ta. tenth bullet",
      "wrapped line without indent",
      "",
      "\tII. eleventh bullet",
      "\t\t1. twelfth bullet",
      "",
      "\t\t\t* thirteenth bullet",
      "",
      "\t\t\t\t+ fourteenth bullet",
      "",
      "\t\t\ta. fifteenth bullet",
      "",
      "\t\t2. sixteenth bullet",
      "",
      "\t\t\t1. seventeenth bullet",
      "",
      "\t\t\t2. eighteenth bullet",
      "\t\t\t\t wrapped line",
      "",
      "\tnormal indented line",
      "next normal line",
      "",
      "1. nineteenth bullet",
      "",
      "x. twentieth bullet",
      "",
      "",
      "i. twenty-first bullet",
      "- twenty-second bullet",
      "",
      "",
      "v. twenty-third bullet",
    }, helpers.get_lines())
  end)

  it("visually renumbers a nested list", function()
    vim.g.bullets_line_spacing = 2
    helpers.new_buffer({
      "# Hello there",
      "0. zero bullet",
      "",
      "X. first bullet",
      "",
      "- second bullet",
      "\twrapped line",
      "",
      "a. third bullet",
      "",
      "I. fourth bullet",
      "",
      "\tV. fifth bullet",
      "",
      "\t\tB. sixth bullet",
      "",
      "\t* seventh bullet",
      "",
      "\t\ti. eighth bullet",
      "",
      "\t\tx. ninth bullet",
      "\t\t\t wrapped line",
      "",
      "\t\t\ta. tenth bullet",
      "wrapped line without indent",
      "",
      "\tC. eleventh bullet",
      "\t\t0. twelfth bullet",
      "",
      "\t\t\t* thirteenth bullet",
      "",
      "\t\t\t\t+ fourteenth bullet",
      "",
      "\t\t\td. fifteenth bullet",
      "",
      "\t\ta. sixteenth bullet",
      "",
      "\t\t\t8. seventeenth bullet",
      "",
      "\t\t\t0. eighteenth bullet",
      "\t\t\t\t wrapped line",
      "",
      "\tnormal indented line",
      "next normal line",
      "",
      "1. nineteenth bullet",
      "",
      "x. twentieth bullet",
      "",
      "",
      "v. twenty-first bullet",
      "- twenty-second bullet",
      "",
      "",
      "v. twenty-third bullet",
    })
    -- From line 1, go down 2 (to line 3), select to last line minus 1 (VGk), then renumber
    helpers.feedkeys("gg2jVGkgN")
    assert.are.same({
      "# Hello there",
      "0. zero bullet",
      "",
      "I. first bullet",
      "",
      "- second bullet",
      "\twrapped line",
      "",
      "II. third bullet",
      "",
      "III. fourth bullet",
      "",
      "\tI. fifth bullet",
      "",
      "\t\tA. sixth bullet",
      "",
      "\t* seventh bullet",
      "",
      "\t\ti. eighth bullet",
      "",
      "\t\tii. ninth bullet",
      "\t\t\t wrapped line",
      "",
      "\t\t\ta. tenth bullet",
      "wrapped line without indent",
      "",
      "\tII. eleventh bullet",
      "\t\t1. twelfth bullet",
      "",
      "\t\t\t* thirteenth bullet",
      "",
      "\t\t\t\t+ fourteenth bullet",
      "",
      "\t\t\ti. fifteenth bullet",
      "",
      "\t\t2. sixteenth bullet",
      "",
      "\t\t\t1. seventeenth bullet",
      "",
      "\t\t\t2. eighteenth bullet",
      "\t\t\t\t wrapped line",
      "",
      "\tnormal indented line",
      "next normal line",
      "",
      "IV.  nineteenth bullet",
      "",
      "V.   twentieth bullet",
      "",
      "",
      "VI.  twenty-first bullet",
      "- twenty-second bullet",
      "",
      "",
      "v. twenty-third bullet",
    }, helpers.get_lines())
  end)
end)
