name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v6.0.2

    - name: Install system dependencies
      run: sudo apt install vim-gtk3 xvfb

    - name: Set up Ruby via mise
      uses: jdx/mise-action@v4.0.1

    - name: Install gems
      run: bundle install

    - name: Run headless tests
      run: xvfb-run -a bundle exec rspec
